// 365-Day Bible Reading Plan
// Data extracted from prayer guide book. Days will be added as more pages are provided.
const READING_PLAN = [
  // === EARLY WORLD (Days 1-5) ===
  { day: 1, period: "Early World", firstReading: "Genesis 1-2", secondReading: null, psalms: "Psalm 19" },
  { day: 2, period: "Early World", firstReading: "Genesis 3-4", secondReading: null, psalms: "Psalm 104" },
  { day: 3, period: "Early World", firstReading: "Genesis 5-6", secondReading: null, psalms: "Psalm 136" },
  { day: 4, period: "Early World", firstReading: "Genesis 7-9", secondReading: null, psalms: "Psalm 8" },
  { day: 5, period: "Early World", firstReading: "Genesis 10-11", secondReading: null, psalms: "Psalm 9" },

  // === PATRIARCHS (Days 6-26) ===
  { day: 6, period: "Patriarchs", firstReading: "Genesis 12-13", secondReading: "Job 1-2", psalms: "Proverbs 1:1-7" },
  { day: 7, period: "Patriarchs", firstReading: "Genesis 14-15", secondReading: "Job 3-4", psalms: "Proverbs 1:8-19" },
  { day: 8, period: "Patriarchs", firstReading: "Genesis 16-17", secondReading: "Job 5-6", psalms: "Proverbs 1:20-33" },
  { day: 9, period: "Patriarchs", firstReading: "Genesis 18-19", secondReading: "Job 7-8", psalms: "Proverbs 2:1-5" },
  { day: 10, period: "Patriarchs", firstReading: "Genesis 20-21", secondReading: "Job 9-10", psalms: "Proverbs 2:6-8" },
  { day: 11, period: "Patriarchs", firstReading: "Genesis 22-23", secondReading: "Job 11-12", psalms: "Proverbs 2:9-15" },
  { day: 12, period: "Patriarchs", firstReading: "Genesis 24", secondReading: "Job 13-14", psalms: "Proverbs 2:16-19" },
  { day: 13, period: "Patriarchs", firstReading: "Genesis 25-26", secondReading: "Job 15-16", psalms: "Proverbs 2:20-22" },
  { day: 14, period: "Patriarchs", firstReading: "Genesis 27-28", secondReading: "Job 17-18", psalms: "Proverbs 3:1-4" },
  { day: 15, period: "Patriarchs", firstReading: "Genesis 29-30", secondReading: "Job 19-20", psalms: "Proverbs 3:5-6" },
  { day: 16, period: "Patriarchs", firstReading: "Genesis 31-32", secondReading: "Job 21-22", psalms: "Proverbs 3:7-12" },
  { day: 17, period: "Patriarchs", firstReading: "Genesis 33-34", secondReading: "Job 23-24", psalms: "Proverbs 3:13-18" },
  { day: 18, period: "Patriarchs", firstReading: "Genesis 35-36", secondReading: "Job 25-26", psalms: "Proverbs 3:19-24" },
  { day: 19, period: "Patriarchs", firstReading: "Genesis 37", secondReading: "Job 27-28", psalms: "Proverbs 3:25-26" },
  { day: 20, period: "Patriarchs", firstReading: "Genesis 38", secondReading: "Job 29-30", psalms: "Proverbs 3:27-32" },
  { day: 21, period: "Patriarchs", firstReading: "Genesis 39-40", secondReading: "Job 31-32", psalms: "Proverbs 3:33-35" },
  { day: 22, period: "Patriarchs", firstReading: "Genesis 41-42", secondReading: "Job 33-34", psalms: "Proverbs 4:1-9" },
  { day: 23, period: "Patriarchs", firstReading: "Genesis 43-44", secondReading: "Job 35-36", psalms: "Proverbs 4:10-19" },
  { day: 24, period: "Patriarchs", firstReading: "Genesis 45-46", secondReading: "Job 37-38", psalms: "Proverbs 4:20-27" },
  { day: 25, period: "Patriarchs", firstReading: "Genesis 47-48", secondReading: "Job 39-40", psalms: "Psalm 18" },
  { day: 26, period: "Patriarchs", firstReading: "Genesis 49-50", secondReading: "Job 41-42", psalms: "Psalm 12" },

  // === EGYPT AND EXODUS (Days 27-45) ===
  { day: 27, period: "Egypt and Exodus", firstReading: "Exodus 1-2", secondReading: "Leviticus 1", psalms: "Psalm 44" },
  { day: 28, period: "Egypt and Exodus", firstReading: "Exodus 3-4", secondReading: "Leviticus 2-3", psalms: "Psalm 45" },
  { day: 29, period: "Egypt and Exodus", firstReading: "Exodus 5-6", secondReading: "Leviticus 4", psalms: "Psalm 46" },
  { day: 30, period: "Egypt and Exodus", firstReading: "Exodus 7-8", secondReading: "Leviticus 5", psalms: "Psalm 47" },
  { day: 31, period: "Egypt and Exodus", firstReading: "Exodus 9", secondReading: "Leviticus 6", psalms: "Psalm 48" },
  { day: 32, period: "Egypt and Exodus", firstReading: "Exodus 10-11", secondReading: "Leviticus 7", psalms: "Psalm 49" },
  { day: 33, period: "Egypt and Exodus", firstReading: "Exodus 12-13", secondReading: "Leviticus 8", psalms: "Psalm 50" },
  { day: 34, period: "Egypt and Exodus", firstReading: "Exodus 14-15", secondReading: "Leviticus 9", psalms: "Psalm 105" },
  { day: 35, period: "Egypt and Exodus", firstReading: "Exodus 15-16", secondReading: "Leviticus 10", psalms: "Psalm 106" },
  { day: 36, period: "Egypt and Exodus", firstReading: "Exodus 17-18", secondReading: "Leviticus 11", psalms: "Psalm 71" },
  { day: 37, period: "Egypt and Exodus", firstReading: "Exodus 19-20", secondReading: "Leviticus 12", psalms: "Psalm 73" },
  { day: 38, period: "Egypt and Exodus", firstReading: "Exodus 21", secondReading: "Leviticus 13", psalms: "Psalm 74" },
  { day: 39, period: "Egypt and Exodus", firstReading: "Exodus 22", secondReading: "Leviticus 14", psalms: "Psalm 75" },
  { day: 40, period: "Egypt and Exodus", firstReading: "Exodus 23", secondReading: "Leviticus 15", psalms: "Psalm 76" },
  { day: 41, period: "Egypt and Exodus", firstReading: "Exodus 24", secondReading: "Leviticus 16", psalms: "Psalm 77" },
  { day: 42, period: "Egypt and Exodus", firstReading: "Exodus 25-26", secondReading: "Leviticus 17", psalms: "Psalm 78" },
  { day: 43, period: "Egypt and Exodus", firstReading: "Exodus 27-28", secondReading: "Leviticus 19", psalms: "Psalm 119:1-56" },
  { day: 44, period: "Egypt and Exodus", firstReading: "Exodus 29-30", secondReading: "Leviticus 20", psalms: "Psalm 119:57-120" },
  { day: 45, period: "Egypt and Exodus", firstReading: "Exodus 31-32", secondReading: "Leviticus 21", psalms: "Psalm 119:121-176" },
];
