// 365-Day Bible Reading Plan — The Bible in a Year (with Fr. Mike Schmitz)
// Based on The Great Adventure Bible Timeline by Jeff Cavins
const READING_PLAN = [

  // === EARLY WORLD (Days 1-5) ===
  { day: 1, period: "Early World", firstReading: "Genesis 1-2", secondReading: null, psalms: "Psalm 19" },
  { day: 2, period: "Early World", firstReading: "Genesis 3-4", secondReading: null, psalms: "Psalm 104" },
  { day: 3, period: "Early World", firstReading: "Genesis 5-6", secondReading: null, psalms: "Psalm 136" },
  { day: 4, period: "Early World", firstReading: "Genesis 7-9", secondReading: null, psalms: "Psalm 1" },
  { day: 5, period: "Early World", firstReading: "Genesis 10-11", secondReading: null, psalms: "Psalm 2" },

  // === PATRIARCHS (Days 6-26) ===
  { day: 6, period: "Patriarchs", firstReading: "Genesis 12-13", secondReading: "Job 1-2", psalms: "Proverbs 1:1-7" },
  { day: 7, period: "Patriarchs", firstReading: "Genesis 14-15", secondReading: "Job 3-4", psalms: "Proverbs 1:8-19" },
  { day: 8, period: "Patriarchs", firstReading: "Genesis 16-17", secondReading: "Job 5-6", psalms: "Proverbs 1:20-33" },
  { day: 9, period: "Patriarchs", firstReading: "Genesis 18-19", secondReading: "Job 7-8", psalms: "Proverbs 2:1-5" },
  { day: 10, period: "Patriarchs", firstReading: "Genesis 20-21", secondReading: "Job 9-10", psalms: "Proverbs 2:6-8" },
  { day: 11, period: "Patriarchs", firstReading: "Genesis 22-23", secondReading: "Job 11-12", psalms: "Proverbs 2:9-15" },
  { day: 12, period: "Patriarchs", firstReading: "Genesis 24", secondReading: "Job 13-14", psalms: "Proverbs 2:16-19" },
  { day: 13, period: "Patriarchs", firstReading: "Genesis 25-26", secondReading: "Job 15-16", psalms: "Proverbs 2:20-22" },
  { day: 14, period: "Patriarchs", firstReading: "Genesis 27-28", secondReading: "Job 17-18", psalms: "Proverbs 3:1-4" },
  { day: 15, period: "Patriarchs", firstReading: "Genesis 29-30", secondReading: "Job 19-20", psalms: "Proverbs 3:5-8" },
  { day: 16, period: "Patriarchs", firstReading: "Genesis 31-32", secondReading: "Job 21-22", psalms: "Proverbs 3:9-12" },
  { day: 17, period: "Patriarchs", firstReading: "Genesis 33-34", secondReading: "Job 23-24", psalms: "Proverbs 3:13-18" },
  { day: 18, period: "Patriarchs", firstReading: "Genesis 35-36", secondReading: "Job 25-26", psalms: "Proverbs 3:19-24" },
  { day: 19, period: "Patriarchs", firstReading: "Genesis 37", secondReading: "Job 27-28", psalms: "Proverbs 3:25-27" },
  { day: 20, period: "Patriarchs", firstReading: "Genesis 38", secondReading: "Job 29-30", psalms: "Proverbs 3:28-32" },
  { day: 21, period: "Patriarchs", firstReading: "Genesis 39-40", secondReading: "Job 31-32", psalms: "Proverbs 3:33-35" },
  { day: 22, period: "Patriarchs", firstReading: "Genesis 41-42", secondReading: "Job 33-34", psalms: "Proverbs 4:1-9" },
  { day: 23, period: "Patriarchs", firstReading: "Genesis 43-44", secondReading: "Job 35-36", psalms: "Proverbs 4:10-19" },
  { day: 24, period: "Patriarchs", firstReading: "Genesis 45-46", secondReading: "Job 37-38", psalms: "Proverbs 4:20-27" },
  { day: 25, period: "Patriarchs", firstReading: "Genesis 47-48", secondReading: "Job 39-40", psalms: "Psalm 16" },
  { day: 26, period: "Patriarchs", firstReading: "Genesis 49-50", secondReading: "Job 41-42", psalms: "Psalm 17" },

  // === EGYPT AND EXODUS (Days 27-51) ===
  { day: 27, period: "Egypt and Exodus", firstReading: "Exodus 1-2", secondReading: "Leviticus 1", psalms: "Psalm 44" },
  { day: 28, period: "Egypt and Exodus", firstReading: "Exodus 3", secondReading: "Leviticus 2-3", psalms: "Psalm 45" },
  { day: 29, period: "Egypt and Exodus", firstReading: "Exodus 4-5", secondReading: "Leviticus 4", psalms: "Psalm 46" },
  { day: 30, period: "Egypt and Exodus", firstReading: "Exodus 6-7", secondReading: "Leviticus 5", psalms: "Psalm 47" },
  { day: 31, period: "Egypt and Exodus", firstReading: "Exodus 8", secondReading: "Leviticus 6", psalms: "Psalm 48" },
  { day: 32, period: "Egypt and Exodus", firstReading: "Exodus 9", secondReading: "Leviticus 7", psalms: "Psalm 49" },
  { day: 33, period: "Egypt and Exodus", firstReading: "Exodus 10-11", secondReading: "Leviticus 8", psalms: "Psalm 50" },
  { day: 34, period: "Egypt and Exodus", firstReading: "Exodus 12", secondReading: "Leviticus 9", psalms: "Psalm 114" },
  { day: 35, period: "Egypt and Exodus", firstReading: "Exodus 13-14", secondReading: "Leviticus 10", psalms: "Psalm 53" },
  { day: 36, period: "Egypt and Exodus", firstReading: "Exodus 15-16", secondReading: "Leviticus 11", psalms: "Psalm 71" },
  { day: 37, period: "Egypt and Exodus", firstReading: "Exodus 17-18", secondReading: "Leviticus 12", psalms: "Psalm 73" },
  { day: 38, period: "Egypt and Exodus", firstReading: "Exodus 19-20", secondReading: "Leviticus 13", psalms: "Psalm 74" },
  { day: 39, period: "Egypt and Exodus", firstReading: "Exodus 21", secondReading: "Leviticus 14", psalms: "Psalm 75" },
  { day: 40, period: "Egypt and Exodus", firstReading: "Exodus 22", secondReading: "Leviticus 15", psalms: "Psalm 76" },
  { day: 41, period: "Egypt and Exodus", firstReading: "Exodus 23", secondReading: "Leviticus 16", psalms: "Psalm 77" },
  { day: 42, period: "Egypt and Exodus", firstReading: "Exodus 24", secondReading: "Leviticus 17-18", psalms: "Psalm 78" },
  { day: 43, period: "Egypt and Exodus", firstReading: "Exodus 25-26", secondReading: "Leviticus 19", psalms: "Psalm 79" },
  { day: 44, period: "Egypt and Exodus", firstReading: "Exodus 27-28", secondReading: "Leviticus 20", psalms: "Psalm 119:1-88" },
  { day: 45, period: "Egypt and Exodus", firstReading: "Exodus 29", secondReading: "Leviticus 21", psalms: "Psalm 119:89-176" },
  { day: 46, period: "Egypt and Exodus", firstReading: "Exodus 30-31", secondReading: "Leviticus 22", psalms: "Psalm 115" },
  { day: 47, period: "Egypt and Exodus", firstReading: "Exodus 32", secondReading: "Leviticus 23", psalms: "Psalm 80" },
  { day: 48, period: "Egypt and Exodus", firstReading: "Exodus 33-34", secondReading: "Leviticus 24", psalms: "Psalm 81" },
  { day: 49, period: "Egypt and Exodus", firstReading: "Exodus 35-36", secondReading: "Leviticus 25", psalms: "Psalm 82" },
  { day: 50, period: "Egypt and Exodus", firstReading: "Exodus 37-38", secondReading: "Leviticus 26", psalms: "Psalm 83" },
  { day: 51, period: "Egypt and Exodus", firstReading: "Exodus 39-40", secondReading: "Leviticus 27", psalms: "Psalm 84" },

  // === DESERT WANDERINGS (Days 52-80) ===
  { day: 52, period: "Desert Wanderings", firstReading: "Numbers 1", secondReading: "Deuteronomy 1", psalms: "Psalm 85" },
  { day: 53, period: "Desert Wanderings", firstReading: "Numbers 2", secondReading: "Deuteronomy 2", psalms: "Psalm 87" },
  { day: 54, period: "Desert Wanderings", firstReading: "Numbers 3", secondReading: "Deuteronomy 3", psalms: "Psalm 88" },
  { day: 55, period: "Desert Wanderings", firstReading: "Numbers 4", secondReading: "Deuteronomy 4", psalms: "Psalm 89" },
  { day: 56, period: "Desert Wanderings", firstReading: "Numbers 5", secondReading: "Deuteronomy 5", psalms: "Psalm 90" },
  { day: 57, period: "Desert Wanderings", firstReading: "Numbers 6", secondReading: "Deuteronomy 6", psalms: "Psalm 91" },
  { day: 58, period: "Desert Wanderings", firstReading: "Numbers 7", secondReading: "Deuteronomy 7", psalms: "Psalm 92" },
  { day: 59, period: "Desert Wanderings", firstReading: "Numbers 8-9", secondReading: "Deuteronomy 8", psalms: "Psalm 93" },
  { day: 60, period: "Desert Wanderings", firstReading: "Numbers 10", secondReading: "Deuteronomy 9", psalms: "Psalm 10" },
  { day: 61, period: "Desert Wanderings", firstReading: "Numbers 11", secondReading: "Deuteronomy 10", psalms: "Psalm 33" },
  { day: 62, period: "Desert Wanderings", firstReading: "Numbers 12-13", secondReading: "Deuteronomy 11", psalms: "Psalm 94" },
  { day: 63, period: "Desert Wanderings", firstReading: "Numbers 14", secondReading: "Deuteronomy 12", psalms: "Psalm 95" },
  { day: 64, period: "Desert Wanderings", firstReading: "Numbers 15", secondReading: "Deuteronomy 13-14", psalms: "Psalm 96" },
  { day: 65, period: "Desert Wanderings", firstReading: "Numbers 16", secondReading: "Deuteronomy 15-16", psalms: "Psalm 97" },
  { day: 66, period: "Desert Wanderings", firstReading: "Numbers 17", secondReading: "Deuteronomy 17-18", psalms: "Psalm 98" },
  { day: 67, period: "Desert Wanderings", firstReading: "Numbers 18", secondReading: "Deuteronomy 19-20", psalms: "Psalm 99" },
  { day: 68, period: "Desert Wanderings", firstReading: "Numbers 19-20", secondReading: "Deuteronomy 21", psalms: "Psalm 100" },
  { day: 69, period: "Desert Wanderings", firstReading: "Numbers 21", secondReading: "Deuteronomy 22", psalms: "Psalm 102" },
  { day: 70, period: "Desert Wanderings", firstReading: "Numbers 22", secondReading: "Deuteronomy 23", psalms: "Psalm 105" },
  { day: 71, period: "Desert Wanderings", firstReading: "Numbers 23", secondReading: "Deuteronomy 24-25", psalms: "Psalm 106" },
  { day: 72, period: "Desert Wanderings", firstReading: "Numbers 24-25", secondReading: "Deuteronomy 26", psalms: "Psalm 107" },
  { day: 73, period: "Desert Wanderings", firstReading: "Numbers 26", secondReading: "Deuteronomy 27", psalms: "Psalm 111" },
  { day: 74, period: "Desert Wanderings", firstReading: "Numbers 27-28", secondReading: "Deuteronomy 28", psalms: "Psalm 112" },
  { day: 75, period: "Desert Wanderings", firstReading: "Numbers 29-30", secondReading: "Deuteronomy 29", psalms: "Psalm 113" },
  { day: 76, period: "Desert Wanderings", firstReading: "Numbers 31", secondReading: "Deuteronomy 30", psalms: "Psalm 116" },
  { day: 77, period: "Desert Wanderings", firstReading: "Numbers 32", secondReading: "Deuteronomy 31", psalms: "Psalm 117" },
  { day: 78, period: "Desert Wanderings", firstReading: "Numbers 33", secondReading: "Deuteronomy 32", psalms: "Psalm 118" },
  { day: 79, period: "Desert Wanderings", firstReading: "Numbers 34", secondReading: "Deuteronomy 33", psalms: "Psalm 120" },
  { day: 80, period: "Desert Wanderings", firstReading: "Numbers 35-36", secondReading: "Deuteronomy 34", psalms: "Psalm 121" },

  // === CONQUEST AND JUDGES (Days 81-98) ===
  { day: 81, period: "Conquest and Judges", firstReading: "Joshua 1-4", secondReading: null, psalms: "Psalm 123" },
  { day: 82, period: "Conquest and Judges", firstReading: "Joshua 5-7", secondReading: null, psalms: "Psalm 125" },
  { day: 83, period: "Conquest and Judges", firstReading: "Joshua 8-9", secondReading: null, psalms: "Psalm 126" },
  { day: 84, period: "Conquest and Judges", firstReading: "Joshua 10-11", secondReading: null, psalms: "Psalm 128" },
  { day: 85, period: "Conquest and Judges", firstReading: "Joshua 12-14", secondReading: null, psalms: "Psalm 129" },
  { day: 86, period: "Conquest and Judges", firstReading: "Joshua 15-18", secondReading: null, psalms: "Psalm 130" },
  { day: 87, period: "Conquest and Judges", firstReading: "Joshua 19-21", secondReading: null, psalms: "Psalm 131" },
  { day: 88, period: "Conquest and Judges", firstReading: "Joshua 22-24", secondReading: null, psalms: "Psalm 132" },
  { day: 89, period: "Conquest and Judges", firstReading: "Judges 1-3", secondReading: "Ruth 1", psalms: "Psalm 133" },
  { day: 90, period: "Conquest and Judges", firstReading: "Judges 4-5", secondReading: "Ruth 2", psalms: "Psalm 134" },
  { day: 91, period: "Conquest and Judges", firstReading: "Judges 6-8", secondReading: "Ruth 3", psalms: "Psalm 135" },
  { day: 92, period: "Conquest and Judges", firstReading: "Judges 9-11", secondReading: "Ruth 4", psalms: "Psalm 137" },
  { day: 93, period: "Conquest and Judges", firstReading: "Judges 12-15", secondReading: null, psalms: "Psalm 146" },
  { day: 94, period: "Conquest and Judges", firstReading: "Judges 16-18", secondReading: null, psalms: "Psalm 147" },
  { day: 95, period: "Conquest and Judges", firstReading: "Judges 19-21", secondReading: null, psalms: "Psalm 148" },
  { day: 96, period: "Conquest and Judges", firstReading: "1 Samuel 1-2", secondReading: null, psalms: "Psalm 149" },
  { day: 97, period: "Conquest and Judges", firstReading: "1 Samuel 3-5", secondReading: null, psalms: "Psalm 150" },
  { day: 98, period: "Conquest and Judges", firstReading: "1 Samuel 6-8", secondReading: null, psalms: "Psalm 86" },

  // === MESSIANIC CHECKPOINT (Days 99-105) ===
  { day: 99, period: "Messianic Checkpoint", firstReading: "John 1-3", secondReading: null, psalms: "Proverbs 5:1-6" },
  { day: 100, period: "Messianic Checkpoint", firstReading: "John 4-6", secondReading: null, psalms: "Proverbs 5:7-14" },
  { day: 101, period: "Messianic Checkpoint", firstReading: "John 7-9", secondReading: null, psalms: "Proverbs 5:15-23" },
  { day: 102, period: "Messianic Checkpoint", firstReading: "John 10-12", secondReading: null, psalms: "Proverbs 6:1-11" },
  { day: 103, period: "Messianic Checkpoint", firstReading: "John 13-15", secondReading: null, psalms: "Proverbs 6:12-19" },
  { day: 104, period: "Messianic Checkpoint", firstReading: "John 16-18", secondReading: null, psalms: "Proverbs 6:20-24" },
  { day: 105, period: "Messianic Checkpoint", firstReading: "John 19-21", secondReading: null, psalms: "Proverbs 6:25-35" },

  // === ROYAL KINGDOM (Days 106-153) ===
  { day: 106, period: "Royal Kingdom", firstReading: "1 Samuel 9-10", secondReading: null, psalms: "Psalm 50" },
  { day: 107, period: "Royal Kingdom", firstReading: "1 Samuel 11-12", secondReading: null, psalms: "Psalm 55" },
  { day: 108, period: "Royal Kingdom", firstReading: "1 Samuel 13-14", secondReading: null, psalms: "Psalm 58" },
  { day: 109, period: "Royal Kingdom", firstReading: "1 Samuel 15-16", secondReading: null, psalms: "Psalm 61" },
  { day: 110, period: "Royal Kingdom", firstReading: "1 Samuel 17", secondReading: null, psalms: "Psalm 12" },
  { day: 111, period: "Royal Kingdom", firstReading: "1 Samuel 18-19", secondReading: null, psalms: "Psalm 59" },
  { day: 112, period: "Royal Kingdom", firstReading: "1 Samuel 20", secondReading: null, psalms: "Psalm 142" },
  { day: 113, period: "Royal Kingdom", firstReading: "1 Samuel 21-22", secondReading: null, psalms: "Psalm 52" },
  { day: 114, period: "Royal Kingdom", firstReading: "1 Samuel 23", secondReading: null, psalms: "Psalm 54" },
  { day: 115, period: "Royal Kingdom", firstReading: "1 Samuel 24", secondReading: null, psalms: "Psalm 57" },
  { day: 116, period: "Royal Kingdom", firstReading: "1 Samuel 25", secondReading: null, psalms: "Psalm 63" },
  { day: 117, period: "Royal Kingdom", firstReading: "1 Samuel 26", secondReading: null, psalms: "Psalm 56" },
  { day: 118, period: "Royal Kingdom", firstReading: "1 Samuel 27-28", secondReading: null, psalms: "Psalm 34" },
  { day: 119, period: "Royal Kingdom", firstReading: "1 Samuel 29-31", secondReading: null, psalms: "Psalm 18" },
  { day: 120, period: "Royal Kingdom", firstReading: "2 Samuel 1", secondReading: "1 Chronicles 1", psalms: "Psalm 13" },
  { day: 121, period: "Royal Kingdom", firstReading: "2 Samuel 2", secondReading: "1 Chronicles 2", psalms: "Psalm 24" },
  { day: 122, period: "Royal Kingdom", firstReading: "2 Samuel 3", secondReading: "1 Chronicles 3-4", psalms: "Psalm 25" },
  { day: 123, period: "Royal Kingdom", firstReading: "2 Samuel 4", secondReading: "1 Chronicles 5-6", psalms: "Psalm 26" },
  { day: 124, period: "Royal Kingdom", firstReading: "2 Samuel 5", secondReading: "1 Chronicles 7-8", psalms: "Psalm 27" },
  { day: 125, period: "Royal Kingdom", firstReading: "2 Samuel 6-7", secondReading: "1 Chronicles 9", psalms: "Psalm 89" },
  { day: 126, period: "Royal Kingdom", firstReading: "2 Samuel 8", secondReading: "1 Chronicles 10-11", psalms: "Psalm 60" },
  { day: 127, period: "Royal Kingdom", firstReading: "2 Samuel 9", secondReading: "1 Chronicles 12", psalms: "Psalm 28" },
  { day: 128, period: "Royal Kingdom", firstReading: "2 Samuel 10", secondReading: "1 Chronicles 13", psalms: "Psalm 31" },
  { day: 129, period: "Royal Kingdom", firstReading: "2 Samuel 11", secondReading: "1 Chronicles 14-15", psalms: "Psalm 32" },
  { day: 130, period: "Royal Kingdom", firstReading: "2 Samuel 12", secondReading: "1 Chronicles 16", psalms: "Psalm 51" },
  { day: 131, period: "Royal Kingdom", firstReading: "2 Samuel 13", secondReading: "1 Chronicles 17", psalms: "Psalm 35" },
  { day: 132, period: "Royal Kingdom", firstReading: "2 Samuel 14", secondReading: "1 Chronicles 18", psalms: "Psalm 14" },
  { day: 133, period: "Royal Kingdom", firstReading: "2 Samuel 15", secondReading: "1 Chronicles 19-20", psalms: "Psalm 3" },
  { day: 134, period: "Royal Kingdom", firstReading: "2 Samuel 16", secondReading: "1 Chronicles 21", psalms: "Psalm 15" },
  { day: 135, period: "Royal Kingdom", firstReading: "2 Samuel 17", secondReading: "1 Chronicles 22", psalms: "Psalm 36" },
  { day: 136, period: "Royal Kingdom", firstReading: "2 Samuel 18", secondReading: "1 Chronicles 23", psalms: "Psalm 37" },
  { day: 137, period: "Royal Kingdom", firstReading: "2 Samuel 19", secondReading: "1 Chronicles 24", psalms: "Psalm 38" },
  { day: 138, period: "Royal Kingdom", firstReading: "2 Samuel 20", secondReading: "1 Chronicles 25", psalms: "Psalm 39" },
  { day: 139, period: "Royal Kingdom", firstReading: "2 Samuel 21", secondReading: "1 Chronicles 26", psalms: "Psalm 40" },
  { day: 140, period: "Royal Kingdom", firstReading: "2 Samuel 22", secondReading: "1 Chronicles 27", psalms: "Psalm 41" },
  { day: 141, period: "Royal Kingdom", firstReading: "2 Samuel 23", secondReading: "1 Chronicles 28", psalms: "Psalm 42" },
  { day: 142, period: "Royal Kingdom", firstReading: "2 Samuel 24", secondReading: "1 Chronicles 29", psalms: "Psalm 30" },
  { day: 143, period: "Royal Kingdom", firstReading: "1 Kings 1", secondReading: "2 Chronicles 1", psalms: "Psalm 43" },
  { day: 144, period: "Royal Kingdom", firstReading: "1 Kings 2", secondReading: "2 Chronicles 2-3", psalms: "Psalm 62" },
  { day: 145, period: "Royal Kingdom", firstReading: "1 Kings 3", secondReading: "2 Chronicles 4-5", psalms: "Psalm 64" },
  { day: 146, period: "Royal Kingdom", firstReading: "1 Kings 4", secondReading: "2 Chronicles 6", psalms: "Psalm 65" },
  { day: 147, period: "Royal Kingdom", firstReading: "1 Kings 5", secondReading: "2 Chronicles 7-8", psalms: "Psalm 66" },
  { day: 148, period: "Royal Kingdom", firstReading: "1 Kings 6", secondReading: "2 Chronicles 9", psalms: "Psalm 4" },
  { day: 149, period: "Royal Kingdom", firstReading: "1 Kings 7", secondReading: "Ecclesiastes 1-2", psalms: "Psalm 5" },
  { day: 150, period: "Royal Kingdom", firstReading: "1 Kings 8", secondReading: "Ecclesiastes 3-5", psalms: "Psalm 6" },
  { day: 151, period: "Royal Kingdom", firstReading: "1 Kings 9", secondReading: "Ecclesiastes 6-7", psalms: "Psalm 7" },
  { day: 152, period: "Royal Kingdom", firstReading: "1 Kings 10", secondReading: "Ecclesiastes 8-9", psalms: "Psalm 8" },
  { day: 153, period: "Royal Kingdom", firstReading: "1 Kings 11", secondReading: "Ecclesiastes 10-12", psalms: "Psalm 9" },

  // === MESSIANIC CHECKPOINT (Days 154-161) ===
  { day: 154, period: "Messianic Checkpoint", firstReading: "Mark 1-2", secondReading: null, psalms: "Psalm 11" },
  { day: 155, period: "Messianic Checkpoint", firstReading: "Mark 3-4", secondReading: null, psalms: "Psalm 20" },
  { day: 156, period: "Messianic Checkpoint", firstReading: "Mark 5-6", secondReading: null, psalms: "Psalm 21" },
  { day: 157, period: "Messianic Checkpoint", firstReading: "Mark 7-8", secondReading: null, psalms: "Psalm 23" },
  { day: 158, period: "Messianic Checkpoint", firstReading: "Mark 9-10", secondReading: null, psalms: "Psalm 29" },
  { day: 159, period: "Messianic Checkpoint", firstReading: "Mark 11-12", secondReading: null, psalms: "Psalm 67" },
  { day: 160, period: "Messianic Checkpoint", firstReading: "Mark 13-14", secondReading: null, psalms: "Psalm 68" },
  { day: 161, period: "Messianic Checkpoint", firstReading: "Mark 15-16", secondReading: null, psalms: "Psalm 22" },

  // === DIVIDED KINGDOM (Days 162-182) ===
  { day: 162, period: "Divided Kingdom", firstReading: "1 Kings 12", secondReading: "2 Chronicles 10-11", psalms: "Song of Solomon 1" },
  { day: 163, period: "Divided Kingdom", firstReading: "1 Kings 13", secondReading: "2 Chronicles 12-13", psalms: "Song of Solomon 2" },
  { day: 164, period: "Divided Kingdom", firstReading: "1 Kings 14", secondReading: "2 Chronicles 14-15", psalms: "Song of Solomon 3" },
  { day: 165, period: "Divided Kingdom", firstReading: "1 Kings 15-16", secondReading: "2 Chronicles 16-17", psalms: "Song of Solomon 4" },
  { day: 166, period: "Divided Kingdom", firstReading: "1 Kings 17-18", secondReading: "2 Chronicles 18-19", psalms: "Song of Solomon 5" },
  { day: 167, period: "Divided Kingdom", firstReading: "1 Kings 19-20", secondReading: "2 Chronicles 20", psalms: "Song of Solomon 6" },
  { day: 168, period: "Divided Kingdom", firstReading: "1 Kings 21", secondReading: "2 Chronicles 21-22", psalms: "Song of Solomon 7" },
  { day: 169, period: "Divided Kingdom", firstReading: "1 Kings 22", secondReading: "2 Chronicles 23", psalms: "Song of Solomon 8" },
  { day: 170, period: "Divided Kingdom", firstReading: "2 Kings 1", secondReading: "2 Chronicles 24", psalms: "Psalm 69" },
  { day: 171, period: "Divided Kingdom", firstReading: "2 Kings 2", secondReading: "2 Chronicles 25", psalms: "Psalm 70" },
  { day: 172, period: "Divided Kingdom", firstReading: "2 Kings 3", secondReading: "2 Chronicles 26-27", psalms: "Psalm 72" },
  { day: 173, period: "Divided Kingdom", firstReading: "2 Kings 4", secondReading: "2 Chronicles 28", psalms: "Psalm 127" },
  { day: 174, period: "Divided Kingdom", firstReading: "2 Kings 5", secondReading: "Hosea 1-3", psalms: "Psalm 101" },
  { day: 175, period: "Divided Kingdom", firstReading: "2 Kings 6-7", secondReading: "Hosea 4-7", psalms: "Psalm 103" },
  { day: 176, period: "Divided Kingdom", firstReading: "2 Kings 8", secondReading: "Hosea 8-10", psalms: "Psalm 108" },
  { day: 177, period: "Divided Kingdom", firstReading: "2 Kings 9", secondReading: "Hosea 11-14", psalms: "Psalm 109" },
  { day: 178, period: "Divided Kingdom", firstReading: "2 Kings 10", secondReading: "Amos 1-3", psalms: "Psalm 110" },
  { day: 179, period: "Divided Kingdom", firstReading: "2 Kings 11-12", secondReading: "Amos 4-6", psalms: "Psalm 122" },
  { day: 180, period: "Divided Kingdom", firstReading: "2 Kings 13-14", secondReading: "Amos 7-9", psalms: "Psalm 124" },
  { day: 181, period: "Divided Kingdom", firstReading: "2 Kings 15", secondReading: "Jonah 1-4", psalms: "Psalm 138" },
  { day: 182, period: "Divided Kingdom", firstReading: "2 Kings 16", secondReading: "Micah 1-4", psalms: "Psalm 139" },

  // === EXILE (Days 183-257) ===
  { day: 183, period: "Exile", firstReading: "2 Kings 17", secondReading: "Micah 5-7", psalms: "Psalm 140" },
  { day: 184, period: "Exile", firstReading: "2 Kings 18", secondReading: "2 Chronicles 29", psalms: "Psalm 141" },
  { day: 185, period: "Exile", firstReading: "2 Kings 19", secondReading: "2 Chronicles 30", psalms: "Psalm 143" },
  { day: 186, period: "Exile", firstReading: "2 Kings 20", secondReading: "2 Chronicles 31", psalms: "Psalm 144" },
  { day: 187, period: "Exile", firstReading: "2 Kings 21", secondReading: "2 Chronicles 32", psalms: "Psalm 145" },
  { day: 188, period: "Exile", firstReading: "2 Kings 22", secondReading: "2 Chronicles 33", psalms: "Proverbs 7" },
  { day: 189, period: "Exile", firstReading: "2 Kings 23", secondReading: "2 Chronicles 34", psalms: "Proverbs 8:1-21" },
  { day: 190, period: "Exile", firstReading: "2 Kings 24", secondReading: "2 Chronicles 35", psalms: "Proverbs 8:22-36" },
  { day: 191, period: "Exile", firstReading: "2 Kings 25", secondReading: "2 Chronicles 36", psalms: "Proverbs 9:1-6" },
  { day: 192, period: "Exile", firstReading: "Isaiah 1-2", secondReading: "Tobit 1-2", psalms: "Proverbs 9:7-12" },
  { day: 193, period: "Exile", firstReading: "Isaiah 3-4", secondReading: "Tobit 3-4", psalms: "Proverbs 9:13-18" },
  { day: 194, period: "Exile", firstReading: "Isaiah 5-6", secondReading: "Tobit 5-6", psalms: "Proverbs 10:1-4" },
  { day: 195, period: "Exile", firstReading: "Isaiah 7-8", secondReading: "Tobit 7-9", psalms: "Proverbs 10:5-8" },
  { day: 196, period: "Exile", firstReading: "Isaiah 9-10", secondReading: "Tobit 10-12", psalms: "Proverbs 10:9-12" },
  { day: 197, period: "Exile", firstReading: "Isaiah 11-13", secondReading: "Tobit 13-14", psalms: "Proverbs 10:13-16" },
  { day: 198, period: "Exile", firstReading: "Isaiah 14-15", secondReading: "Joel 1-2", psalms: "Proverbs 10:17-20" },
  { day: 199, period: "Exile", firstReading: "Isaiah 16-17", secondReading: "Joel 3", psalms: "Proverbs 10:21-24" },
  { day: 200, period: "Exile", firstReading: "Isaiah 18-20", secondReading: "Nahum 1-2", psalms: "Proverbs 10:25-28" },
  { day: 201, period: "Exile", firstReading: "Isaiah 21-22", secondReading: "Nahum 3", psalms: "Proverbs 10:29-32" },
  { day: 202, period: "Exile", firstReading: "Isaiah 23-24", secondReading: "Habakkuk 1-2", psalms: "Proverbs 11:1-4" },
  { day: 203, period: "Exile", firstReading: "Isaiah 25-27", secondReading: "Habakkuk 3", psalms: "Proverbs 11:5-8" },
  { day: 204, period: "Exile", firstReading: "Isaiah 28-29", secondReading: "Zephaniah 1-2", psalms: "Proverbs 11:9-12" },
  { day: 205, period: "Exile", firstReading: "Isaiah 30-31", secondReading: "Zephaniah 3", psalms: "Proverbs 11:13-16" },
  { day: 206, period: "Exile", firstReading: "Isaiah 32-33", secondReading: "Baruch 1-2", psalms: "Proverbs 11:17-20" },
  { day: 207, period: "Exile", firstReading: "Isaiah 34-36", secondReading: "Baruch 3-4", psalms: "Proverbs 11:21-24" },
  { day: 208, period: "Exile", firstReading: "Isaiah 37-38", secondReading: "Baruch 5-6", psalms: "Proverbs 11:25-28" },
  { day: 209, period: "Exile", firstReading: "Isaiah 39-40", secondReading: "Ezekiel 1", psalms: "Proverbs 11:29-31" },
  { day: 210, period: "Exile", firstReading: "Isaiah 41-42", secondReading: "Ezekiel 2-3", psalms: "Proverbs 12:1-4" },
  { day: 211, period: "Exile", firstReading: "Isaiah 43-44", secondReading: "Ezekiel 4-5", psalms: "Proverbs 12:5-8" },
  { day: 212, period: "Exile", firstReading: "Isaiah 45-46", secondReading: "Ezekiel 6-7", psalms: "Proverbs 12:9-12" },
  { day: 213, period: "Exile", firstReading: "Isaiah 47-48", secondReading: "Ezekiel 8-9", psalms: "Proverbs 12:13-16" },
  { day: 214, period: "Exile", firstReading: "Isaiah 49-50", secondReading: "Ezekiel 10-11", psalms: "Proverbs 12:17-20" },
  { day: 215, period: "Exile", firstReading: "Isaiah 51-52", secondReading: "Ezekiel 12-13", psalms: "Proverbs 12:21-24" },
  { day: 216, period: "Exile", firstReading: "Isaiah 53-54", secondReading: "Ezekiel 14-15", psalms: "Proverbs 12:25-28" },
  { day: 217, period: "Exile", firstReading: "Isaiah 55-56", secondReading: "Ezekiel 16", psalms: "Proverbs 13:1-4" },
  { day: 218, period: "Exile", firstReading: "Isaiah 57-58", secondReading: "Ezekiel 17-18", psalms: "Proverbs 13:5-8" },
  { day: 219, period: "Exile", firstReading: "Isaiah 59-60", secondReading: "Ezekiel 19", psalms: "Proverbs 13:9-12" },
  { day: 220, period: "Exile", firstReading: "Isaiah 61-62", secondReading: "Ezekiel 20", psalms: "Proverbs 13:13-16" },
  { day: 221, period: "Exile", firstReading: "Isaiah 63-64", secondReading: "Ezekiel 21-22", psalms: "Proverbs 13:17-20" },
  { day: 222, period: "Exile", firstReading: "Isaiah 65", secondReading: "Ezekiel 23-24", psalms: "Proverbs 13:21-25" },
  { day: 223, period: "Exile", firstReading: "Isaiah 66", secondReading: "Ezekiel 25-26", psalms: "Proverbs 14:1-4" },
  { day: 224, period: "Exile", firstReading: "Jeremiah 1", secondReading: "Ezekiel 27", psalms: "Proverbs 14:5-8" },
  { day: 225, period: "Exile", firstReading: "Jeremiah 2", secondReading: "Ezekiel 28", psalms: "Proverbs 14:9-12" },
  { day: 226, period: "Exile", firstReading: "Jeremiah 3", secondReading: "Ezekiel 29-30", psalms: "Proverbs 14:13-16" },
  { day: 227, period: "Exile", firstReading: "Jeremiah 4", secondReading: "Ezekiel 31-32", psalms: "Proverbs 14:17-20" },
  { day: 228, period: "Exile", firstReading: "Jeremiah 5", secondReading: "Ezekiel 33", psalms: "Proverbs 14:21-24" },
  { day: 229, period: "Exile", firstReading: "Jeremiah 6", secondReading: "Ezekiel 34-35", psalms: "Proverbs 14:25-28" },
  { day: 230, period: "Exile", firstReading: "Jeremiah 7", secondReading: "Ezekiel 36", psalms: "Proverbs 14:29-32" },
  { day: 231, period: "Exile", firstReading: "Jeremiah 8", secondReading: "Ezekiel 37-38", psalms: "Proverbs 14:33-35" },
  { day: 232, period: "Exile", firstReading: "Jeremiah 9", secondReading: "Ezekiel 39", psalms: "Proverbs 15:1-4" },
  { day: 233, period: "Exile", firstReading: "Jeremiah 10-11", secondReading: "Ezekiel 40", psalms: "Proverbs 15:5-8" },
  { day: 234, period: "Exile", firstReading: "Jeremiah 12-13", secondReading: "Ezekiel 41-42", psalms: "Proverbs 15:9-12" },
  { day: 235, period: "Exile", firstReading: "Jeremiah 14-15", secondReading: "Ezekiel 43-44", psalms: "Proverbs 15:13-16" },
  { day: 236, period: "Exile", firstReading: "Jeremiah 16-17", secondReading: "Ezekiel 45-46", psalms: "Proverbs 15:17-20" },
  { day: 237, period: "Exile", firstReading: "Jeremiah 18-19", secondReading: "Ezekiel 47-48", psalms: "Proverbs 15:21-24" },
  { day: 238, period: "Exile", firstReading: "Jeremiah 20-21", secondReading: "Daniel 1-2", psalms: "Proverbs 15:25-28" },
  { day: 239, period: "Exile", firstReading: "Jeremiah 22", secondReading: "Daniel 3", psalms: "Proverbs 15:29-33" },
  { day: 240, period: "Exile", firstReading: "Jeremiah 23", secondReading: "Daniel 4-5", psalms: "Proverbs 16:1-4" },
  { day: 241, period: "Exile", firstReading: "Jeremiah 24-25", secondReading: "Daniel 6-7", psalms: "Proverbs 16:5-8" },
  { day: 242, period: "Exile", firstReading: "Jeremiah 26-27", secondReading: "Daniel 8-9", psalms: "Proverbs 16:9-12" },
  { day: 243, period: "Exile", firstReading: "Jeremiah 28-29", secondReading: "Daniel 10-11", psalms: "Proverbs 16:13-16" },
  { day: 244, period: "Exile", firstReading: "Jeremiah 30", secondReading: "Daniel 12-13", psalms: "Proverbs 16:17-20" },
  { day: 245, period: "Exile", firstReading: "Jeremiah 31", secondReading: "Daniel 14", psalms: "Proverbs 16:21-24" },
  { day: 246, period: "Exile", firstReading: "Jeremiah 32", secondReading: "Judith 1-2", psalms: "Proverbs 16:25-28" },
  { day: 247, period: "Exile", firstReading: "Jeremiah 33-34", secondReading: "Judith 3-5", psalms: "Proverbs 16:29-33" },
  { day: 248, period: "Exile", firstReading: "Jeremiah 35-36", secondReading: "Judith 6-7", psalms: "Proverbs 17:1-4" },
  { day: 249, period: "Exile", firstReading: "Jeremiah 37-38", secondReading: "Judith 8-9", psalms: "Proverbs 17:5-8" },
  { day: 250, period: "Exile", firstReading: "Jeremiah 39-40", secondReading: "Judith 10-11", psalms: "Proverbs 17:9-12" },
  { day: 251, period: "Exile", firstReading: "Jeremiah 41-42", secondReading: "Judith 12-14", psalms: "Proverbs 17:13-16" },
  { day: 252, period: "Exile", firstReading: "Jeremiah 43-44", secondReading: "Judith 15-16", psalms: "Proverbs 17:17-20" },
  { day: 253, period: "Exile", firstReading: "Jeremiah 45-46", secondReading: "Lamentations 1", psalms: "Proverbs 17:21-24" },
  { day: 254, period: "Exile", firstReading: "Jeremiah 47-48", secondReading: "Lamentations 2", psalms: "Proverbs 18:1-4" },
  { day: 255, period: "Exile", firstReading: "Jeremiah 49-50", secondReading: "Lamentations 3", psalms: "Proverbs 18:5-8" },
  { day: 256, period: "Exile", firstReading: "Jeremiah 51", secondReading: "Lamentations 4-5", psalms: "Proverbs 18:9-12" },
  { day: 257, period: "Exile", firstReading: "Jeremiah 52", secondReading: "Obadiah 1", psalms: "Proverbs 18:13-16" },

  // === MESSIANIC CHECKPOINT (Days 258-266) ===
  { day: 258, period: "Messianic Checkpoint", firstReading: "Matthew 1-4", secondReading: null, psalms: "Proverbs 18:17-20" },
  { day: 259, period: "Messianic Checkpoint", firstReading: "Matthew 5-7", secondReading: null, psalms: "Proverbs 18:21-24" },
  { day: 260, period: "Messianic Checkpoint", firstReading: "Matthew 8-10", secondReading: null, psalms: "Proverbs 19:1-4" },
  { day: 261, period: "Messianic Checkpoint", firstReading: "Matthew 11-13", secondReading: null, psalms: "Proverbs 19:5-8" },
  { day: 262, period: "Messianic Checkpoint", firstReading: "Matthew 14-17", secondReading: null, psalms: "Proverbs 19:9-12" },
  { day: 263, period: "Messianic Checkpoint", firstReading: "Matthew 18-21", secondReading: null, psalms: "Proverbs 19:13-16" },
  { day: 264, period: "Messianic Checkpoint", firstReading: "Matthew 22-24", secondReading: null, psalms: "Proverbs 19:17-20" },
  { day: 265, period: "Messianic Checkpoint", firstReading: "Matthew 25-26", secondReading: null, psalms: "Proverbs 19:21-24" },
  { day: 266, period: "Messianic Checkpoint", firstReading: "Matthew 27-28", secondReading: null, psalms: "Proverbs 19:25-29" },

  // === RETURN (Days 267-281) ===
  { day: 267, period: "Return", firstReading: "Ezra 1-2", secondReading: "Haggai 1-2", psalms: "Proverbs 20:1-3" },
  { day: 268, period: "Return", firstReading: "Ezra 3-4", secondReading: "Zechariah 1-3", psalms: "Proverbs 20:4-7" },
  { day: 269, period: "Return", firstReading: "Ezra 5-6", secondReading: "Zechariah 4-6", psalms: "Proverbs 20:8-11" },
  { day: 270, period: "Return", firstReading: "Ezra 7-8", secondReading: "Zechariah 7-8", psalms: "Proverbs 20:12-15" },
  { day: 271, period: "Return", firstReading: "Ezra 9-10", secondReading: "Zechariah 9-11", psalms: "Proverbs 20:16-19" },
  { day: 272, period: "Return", firstReading: "Nehemiah 1-2", secondReading: "Zechariah 12-13", psalms: "Proverbs 20:20-22" },
  { day: 273, period: "Return", firstReading: "Nehemiah 3", secondReading: "Zechariah 14", psalms: "Proverbs 20:23-26" },
  { day: 274, period: "Return", firstReading: "Nehemiah 4-5", secondReading: "Esther 1-2", psalms: "Proverbs 20:27-30" },
  { day: 275, period: "Return", firstReading: "Nehemiah 6-7", secondReading: "Esther 3, 13", psalms: "Proverbs 21:1-4" },
  { day: 276, period: "Return", firstReading: "Nehemiah 8", secondReading: "Esther 4, 14", psalms: "Proverbs 21:5-8" },
  { day: 277, period: "Return", firstReading: "Nehemiah 9", secondReading: "Esther 15, 6-7", psalms: "Proverbs 21:9-12" },
  { day: 278, period: "Return", firstReading: "Nehemiah 10", secondReading: "Esther 8, 16", psalms: "Proverbs 21:13-16" },
  { day: 279, period: "Return", firstReading: "Nehemiah 11", secondReading: "Esther 9-11", psalms: "Proverbs 21:17-20" },
  { day: 280, period: "Return", firstReading: "Nehemiah 12", secondReading: "Esther 10-12", psalms: "Proverbs 21:21-24" },
  { day: 281, period: "Return", firstReading: "Nehemiah 13", secondReading: "Malachi 1-4", psalms: "Proverbs 21:25-28" },

  // === MACCABEAN REVOLT (Days 282-312) ===
  { day: 282, period: "Maccabean Revolt", firstReading: "1 Maccabees 1", secondReading: "Sirach 1-3", psalms: "Proverbs 21:29-31" },
  { day: 283, period: "Maccabean Revolt", firstReading: "1 Maccabees 2", secondReading: "Sirach 4-6", psalms: "Proverbs 22:1-4" },
  { day: 284, period: "Maccabean Revolt", firstReading: "1 Maccabees 3", secondReading: "Sirach 7-9", psalms: "Proverbs 22:5-8" },
  { day: 285, period: "Maccabean Revolt", firstReading: "1 Maccabees 4", secondReading: "Sirach 10-12", psalms: "Proverbs 22:9-12" },
  { day: 286, period: "Maccabean Revolt", firstReading: "1 Maccabees 5", secondReading: "Sirach 13-15", psalms: "Proverbs 22:13-16" },
  { day: 287, period: "Maccabean Revolt", firstReading: "1 Maccabees 6", secondReading: "Sirach 16-18", psalms: "Proverbs 22:17-21" },
  { day: 288, period: "Maccabean Revolt", firstReading: "1 Maccabees 7", secondReading: "Sirach 19-21", psalms: "Proverbs 22:22-25" },
  { day: 289, period: "Maccabean Revolt", firstReading: "1 Maccabees 8", secondReading: "Sirach 22-23", psalms: "Proverbs 22:26-29" },
  { day: 290, period: "Maccabean Revolt", firstReading: "1 Maccabees 9", secondReading: "Sirach 24-25", psalms: "Proverbs 23:1-4" },
  { day: 291, period: "Maccabean Revolt", firstReading: "1 Maccabees 10", secondReading: "Sirach 26-27", psalms: "Proverbs 23:5-8" },
  { day: 292, period: "Maccabean Revolt", firstReading: "1 Maccabees 11", secondReading: "Sirach 28-29", psalms: "Proverbs 23:9-12" },
  { day: 293, period: "Maccabean Revolt", firstReading: "1 Maccabees 12", secondReading: "Sirach 30-31", psalms: "Proverbs 23:13-16" },
  { day: 294, period: "Maccabean Revolt", firstReading: "1 Maccabees 13", secondReading: "Sirach 32-33", psalms: "Proverbs 23:17-21" },
  { day: 295, period: "Maccabean Revolt", firstReading: "1 Maccabees 14", secondReading: "Sirach 34-35", psalms: "Proverbs 23:22-25" },
  { day: 296, period: "Maccabean Revolt", firstReading: "1 Maccabees 15", secondReading: "Sirach 36-37", psalms: "Proverbs 23:26-28" },
  { day: 297, period: "Maccabean Revolt", firstReading: "1 Maccabees 16", secondReading: "Sirach 38-39", psalms: "Proverbs 23:29-35" },
  { day: 298, period: "Maccabean Revolt", firstReading: "2 Maccabees 1", secondReading: "Sirach 40-41", psalms: "Proverbs 24:1-7" },
  { day: 299, period: "Maccabean Revolt", firstReading: "2 Maccabees 2", secondReading: "Sirach 42-44", psalms: "Proverbs 24:8-9" },
  { day: 300, period: "Maccabean Revolt", firstReading: "2 Maccabees 3", secondReading: "Sirach 45-46", psalms: "Proverbs 24:10-12" },
  { day: 301, period: "Maccabean Revolt", firstReading: "2 Maccabees 4", secondReading: "Sirach 47-49", psalms: "Proverbs 24:13-16" },
  { day: 302, period: "Maccabean Revolt", firstReading: "2 Maccabees 5", secondReading: "Sirach 50-51", psalms: "Proverbs 24:17-20" },
  { day: 303, period: "Maccabean Revolt", firstReading: "2 Maccabees 6", secondReading: "Wisdom 1-2", psalms: "Proverbs 24:21-26" },
  { day: 304, period: "Maccabean Revolt", firstReading: "2 Maccabees 7", secondReading: "Wisdom 3-4", psalms: "Proverbs 24:27-29" },
  { day: 305, period: "Maccabean Revolt", firstReading: "2 Maccabees 8", secondReading: "Wisdom 5-6", psalms: "Proverbs 24:30-34" },
  { day: 306, period: "Maccabean Revolt", firstReading: "2 Maccabees 9", secondReading: "Wisdom 7-8", psalms: "Proverbs 25:1-3" },
  { day: 307, period: "Maccabean Revolt", firstReading: "2 Maccabees 10", secondReading: "Wisdom 9-10", psalms: "Proverbs 25:4-7" },
  { day: 308, period: "Maccabean Revolt", firstReading: "2 Maccabees 11", secondReading: "Wisdom 11-12", psalms: "Proverbs 25:8-10" },
  { day: 309, period: "Maccabean Revolt", firstReading: "2 Maccabees 12", secondReading: "Wisdom 13-14", psalms: "Proverbs 25:11-14" },
  { day: 310, period: "Maccabean Revolt", firstReading: "2 Maccabees 13", secondReading: "Wisdom 15-16", psalms: "Proverbs 25:15-17" },
  { day: 311, period: "Maccabean Revolt", firstReading: "2 Maccabees 14", secondReading: "Wisdom 17-18", psalms: "Proverbs 25:18-20" },
  { day: 312, period: "Maccabean Revolt", firstReading: "2 Maccabees 15", secondReading: "Wisdom 19", psalms: "Proverbs 25:21-23" },

  // === MESSIANIC FULFILLMENT (Days 313-321) ===
  { day: 313, period: "Messianic Fulfillment", firstReading: "Luke 1-2", secondReading: null, psalms: "Proverbs 25:24-26" },
  { day: 314, period: "Messianic Fulfillment", firstReading: "Luke 3-5", secondReading: null, psalms: "Proverbs 25:27-28" },
  { day: 315, period: "Messianic Fulfillment", firstReading: "Luke 6-8", secondReading: null, psalms: "Proverbs 26:1-3" },
  { day: 316, period: "Messianic Fulfillment", firstReading: "Luke 9-10", secondReading: null, psalms: "Proverbs 26:4-6" },
  { day: 317, period: "Messianic Fulfillment", firstReading: "Luke 11-12", secondReading: null, psalms: "Proverbs 26:7-9" },
  { day: 318, period: "Messianic Fulfillment", firstReading: "Luke 13-16", secondReading: null, psalms: "Proverbs 26:10-12" },
  { day: 319, period: "Messianic Fulfillment", firstReading: "Luke 17-19", secondReading: null, psalms: "Proverbs 26:13-16" },
  { day: 320, period: "Messianic Fulfillment", firstReading: "Luke 20-22:38", secondReading: null, psalms: "Proverbs 26:17-19" },
  { day: 321, period: "Messianic Fulfillment", firstReading: "Luke 22:39-24", secondReading: null, psalms: "Proverbs 26:20-23" },

  // === THE CHURCH (Days 322-365) ===
  { day: 322, period: "The Church", firstReading: "Acts 1", secondReading: "Romans 1", psalms: "Proverbs 26:24-26" },
  { day: 323, period: "The Church", firstReading: "Acts 2", secondReading: "Romans 2-3", psalms: "Proverbs 26:27-28" },
  { day: 324, period: "The Church", firstReading: "Acts 3", secondReading: "Romans 4-5", psalms: "Proverbs 27:1-3" },
  { day: 325, period: "The Church", firstReading: "Acts 4", secondReading: "Romans 6-7", psalms: "Proverbs 27:4-6" },
  { day: 326, period: "The Church", firstReading: "Acts 5", secondReading: "Romans 8", psalms: "Proverbs 27:7-9" },
  { day: 327, period: "The Church", firstReading: "Acts 6", secondReading: "Romans 9-10", psalms: "Proverbs 27:10-12" },
  { day: 328, period: "The Church", firstReading: "Acts 7", secondReading: "Romans 11-12", psalms: "Proverbs 27:13-14" },
  { day: 329, period: "The Church", firstReading: "Acts 8", secondReading: "Romans 13-14", psalms: "Proverbs 27:15-17" },
  { day: 330, period: "The Church", firstReading: "Acts 9", secondReading: "Romans 15-16", psalms: "Proverbs 27:18-20" },
  { day: 331, period: "The Church", firstReading: "Acts 10", secondReading: "1 Corinthians 1-2", psalms: "Proverbs 27:21-22" },
  { day: 332, period: "The Church", firstReading: "Acts 11", secondReading: "1 Corinthians 3-4", psalms: "Proverbs 27:23-27" },
  { day: 333, period: "The Church", firstReading: "Acts 12", secondReading: "1 Corinthians 5-6", psalms: "Proverbs 28:1-3" },
  { day: 334, period: "The Church", firstReading: "Acts 13", secondReading: "1 Corinthians 7-8", psalms: "Proverbs 28:4-6" },
  { day: 335, period: "The Church", firstReading: "Acts 14", secondReading: "1 Corinthians 9-10", psalms: "Proverbs 28:7-9" },
  { day: 336, period: "The Church", firstReading: "Acts 15", secondReading: "1 Corinthians 11-12", psalms: "Proverbs 28:10-12" },
  { day: 337, period: "The Church", firstReading: "Acts 16", secondReading: "1 Corinthians 13-14", psalms: "Proverbs 28:13-15" },
  { day: 338, period: "The Church", firstReading: "Acts 17", secondReading: "1 Corinthians 15", psalms: "Proverbs 28:16-18" },
  { day: 339, period: "The Church", firstReading: "Acts 18", secondReading: "1 Corinthians 16", psalms: "Proverbs 28:19-21" },
  { day: 340, period: "The Church", firstReading: "Acts 19", secondReading: "2 Corinthians 1-2", psalms: "Proverbs 28:22-24" },
  { day: 341, period: "The Church", firstReading: "Acts 20", secondReading: "2 Corinthians 3-5", psalms: "Proverbs 28:25-28" },
  { day: 342, period: "The Church", firstReading: "Acts 21", secondReading: "2 Corinthians 6-8", psalms: "Proverbs 29:1-4" },
  { day: 343, period: "The Church", firstReading: "Acts 22", secondReading: "2 Corinthians 9-11", psalms: "Proverbs 29:5-7" },
  { day: 344, period: "The Church", firstReading: "Acts 23", secondReading: "2 Corinthians 12-13", psalms: "Proverbs 29:8-11" },
  { day: 345, period: "The Church", firstReading: "Acts 24", secondReading: "Galatians 1-3", psalms: "Proverbs 29:12-14" },
  { day: 346, period: "The Church", firstReading: "Acts 25", secondReading: "Galatians 4-6", psalms: "Proverbs 29:15-17" },
  { day: 347, period: "The Church", firstReading: "Acts 26", secondReading: "Ephesians 1-3", psalms: "Proverbs 29:18-21" },
  { day: 348, period: "The Church", firstReading: "Acts 27", secondReading: "Ephesians 4-6", psalms: "Proverbs 29:22-24" },
  { day: 349, period: "The Church", firstReading: "Acts 28", secondReading: "Philippians 1-2", psalms: "Proverbs 29:25-27" },
  { day: 350, period: "The Church", firstReading: "James 1-2", secondReading: "Philippians 3-4", psalms: "Proverbs 30:1-6" },
  { day: 351, period: "The Church", firstReading: "James 3-5", secondReading: "Colossians 1-2", psalms: "Proverbs 30:7-9" },
  { day: 352, period: "The Church", firstReading: "1 Peter 1-2", secondReading: "Colossians 3-4", psalms: "Proverbs 30:10-14" },
  { day: 353, period: "The Church", firstReading: "1 Peter 3-5", secondReading: "1 Thessalonians 1-3", psalms: "Proverbs 30:15-16" },
  { day: 354, period: "The Church", firstReading: "2 Peter 1-3", secondReading: "1 Thessalonians 4-5", psalms: "Proverbs 30:17-19" },
  { day: 355, period: "The Church", firstReading: "1 John 1-3", secondReading: "2 Thessalonians 1-3", psalms: "Proverbs 30:20-23" },
  { day: 356, period: "The Church", firstReading: "1 John 4-5", secondReading: "1 Timothy 1-3", psalms: "Proverbs 30:24-28" },
  { day: 357, period: "The Church", firstReading: "2 John, 3 John", secondReading: "1 Timothy 4-6", psalms: "Proverbs 30:29-33" },
  { day: 358, period: "The Church", firstReading: "Jude", secondReading: "2 Timothy 1-2", psalms: "Proverbs 31:1-7" },
  { day: 359, period: "The Church", firstReading: "Revelation 1-3", secondReading: "2 Timothy 3-4", psalms: "Proverbs 31:8-9" },
  { day: 360, period: "The Church", firstReading: "Revelation 4-7", secondReading: "Titus 1-3", psalms: "Proverbs 31:10-15" },
  { day: 361, period: "The Church", firstReading: "Revelation 8-11", secondReading: "Philemon", psalms: "Proverbs 31:16-18" },
  { day: 362, period: "The Church", firstReading: "Revelation 12-14", secondReading: "Hebrews 1-4", psalms: "Proverbs 31:19-22" },
  { day: 363, period: "The Church", firstReading: "Revelation 15-17", secondReading: "Hebrews 5-8", psalms: "Proverbs 31:23-25" },
  { day: 364, period: "The Church", firstReading: "Revelation 18-20", secondReading: "Hebrews 9-10", psalms: "Proverbs 31:26-29" },
  { day: 365, period: "The Church", firstReading: "Revelation 21-22", secondReading: "Hebrews 11-13", psalms: "Proverbs 31:30-31" },
];
